language: python
python:
  - 2.7
  - 3.2
install:
  - pip install -r requirements/testing.txt -r requirements/production.txt --use-mirrors
  - python setup.py install
script: python setup.py test
notifications:
    email: mjdorma+travis-ci@gmail.com

