language: python
python:
  - 2.7
#  - 3.2
#before_install:
#  - sudo apt-get update -qq
#  - sudo apt-get install -qq libpcre3
install:
  - python setup.py install 
script: python -m yara.scan -h
#script: python setup.py test
notifications:
    email: mjdorma+travis-ci@gmail.com

